__inline('js/WeixinApi.js');
WeixinApi.ready(function(Api){
    Api.hideToolbar();
});
(function(){
    __inline('js/easeljs-0.7.1.min.js');
    __inline('js/preloadjs-0.4.1.min.js');
    __inline('js/tweenjs-0.5.1.min.js');
    __inline('js/amd.js');
    __inline('js/log.js');
    __inline('js/timer.js');
    __inline('js/score.js');
    __inline('js/gate.js');
    __inline('js/bg.js');
    __inline('js/ball.js');
    __inline('js/player.js');
    __inline('js/keeper.js');
    __inline('js/arrow.js');
    __inline('js/squirrel.js');
    __inline('js/ui.js');
    __inline('js/main.js');
})();